"use client";

import React, { useState } from "react";
import { useRouter } from "next/navigation";
import { useApp } from "@/context/AppContext";
import { Video, ShieldCheck, Mail, Lock, User as UserIcon, Github, Chrome, KeyRound } from "lucide-react";

export default function LoginPage() {
  const { login, loginSSO, register } = useApp();
  const router = useRouter();

  const [isRegister, setIsRegister] = useState(false);
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");
  const [password, setPassword] = useState("");
  const [role, setRole] = useState("ORGANIZER"); // Default to organizer so they can schedule meetings
  
  // MFA (Multi-Factor Auth) Step
  const [showMfa, setShowMfa] = useState(false);
  const [mfaCode, setMfaCode] = useState("");
  const [mfaError, setMfaError] = useState("");
  
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setLoading(true);

    try {
      if (isRegister) {
        const success = await register(email, name, password, role);
        if (success) {
          router.push("/dashboard");
        } else {
          setError("Failed to register. Please check inputs.");
        }
      } else {
        // If email contains "mfa", simulate MFA step
        if (email.includes("mfa")) {
          setShowMfa(true);
          setLoading(false);
          return;
        }

        const success = await login(email, password);
        if (success) {
          router.push("/dashboard");
        } else {
          setError("Invalid email or password.");
        }
      }
    } catch (err) {
      setError("An unexpected error occurred.");
    } finally {
      setLoading(false);
    }
  };

  const handleMfaSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setMfaError("");
    
    // Accept standard mock code "123456"
    if (mfaCode === "123456") {
      setLoading(true);
      login(email, password).then(() => {
        router.push("/dashboard");
      });
    } else {
      setMfaError("Incorrect verification code. Hint: Use 123456");
    }
  };

  const handleSSO = async (provider: string) => {
    setLoading(true);
    try {
      const success = await loginSSO(provider);
      if (success) {
        router.push("/dashboard");
      }
    } catch (err) {
      setError(`SSO authentication via ${provider} failed.`);
    } finally {
      setLoading(false);
    }
  };

  if (showMfa) {
    return (
      <div className="flex-1 flex items-center justify-center bg-[#0B0F19] px-4 font-sans">
        <div className="w-full max-w-md bg-[#111625] border border-white/5 p-8 rounded-2xl shadow-2xl space-y-6 text-center">
          <div className="mx-auto w-12 h-12 bg-accent-blue/10 border border-accent-blue/20 rounded-xl flex items-center justify-center text-accent-blue animate-pulse">
            <KeyRound className="w-6 h-6" />
          </div>
          <div className="space-y-1">
            <h2 className="text-xl font-bold text-white">Multi-Factor Authentication</h2>
            <p className="text-xs text-zinc-400">Enter the 6-digit code generated by your authenticator app.</p>
          </div>

          <form onSubmit={handleMfaSubmit} className="space-y-4">
            <input
              type="text"
              required
              maxLength={6}
              placeholder="e.g. 123456"
              value={mfaCode}
              onChange={(e) => setMfaCode(e.target.value.replace(/\D/g, ""))}
              className="w-full text-center tracking-widest text-lg font-bold bg-white/[0.03] border border-white/5 py-3 rounded-xl outline-none placeholder-zinc-700 text-white focus:border-accent-blue transition-all"
            />
            {mfaError && <p className="text-[11px] text-red-400 font-semibold">{mfaError}</p>}
            <button
              type="submit"
              className="w-full py-3 bg-accent-blue hover:bg-blue-600 rounded-xl text-white text-xs font-bold transition-all shadow-md shadow-accent-blue/10"
            >
              Verify Code
            </button>
            <button
              type="button"
              onClick={() => setShowMfa(false)}
              className="text-xs text-zinc-500 hover:text-zinc-300 font-medium"
            >
              Cancel Login
            </button>
          </form>
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 flex items-center justify-center bg-[#0B0F19] px-4 font-sans">
      <div className="w-full max-w-md bg-[#111625] border border-white/5 p-8 rounded-2xl shadow-2xl space-y-6">
        {/* Brand */}
        <div className="flex flex-col items-center space-y-2 text-center">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-tr from-accent-blue to-accent-purple flex items-center justify-center shadow-lg shadow-accent-blue/20">
            <Video className="w-6 h-6 text-white" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white tracking-tight">Welcome to VibeSync</h2>
            <p className="text-xs text-zinc-500 font-medium">Virtual Meetings & Live Team Workspace</p>
          </div>
        </div>

        {error && (
          <div className="p-3 bg-red-500/10 border border-red-500/20 text-red-400 rounded-xl text-xs text-center font-medium">
            {error}
          </div>
        )}

        {/* Credentials Form */}
        <form onSubmit={handleSubmit} className="space-y-4">
          {isRegister && (
            <div className="space-y-1">
              <label className="text-[10px] text-zinc-400 font-bold uppercase tracking-wider">Full Name</label>
              <div className="relative">
                <UserIcon className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-600" />
                <input
                  type="text"
                  required
                  placeholder="John Doe"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="w-full bg-white/[0.03] border border-white/5 pl-10 pr-4 py-2.5 rounded-xl text-xs text-zinc-200 outline-none focus:border-accent-blue transition-colors"
                />
              </div>
            </div>
          )}

          <div className="space-y-1">
            <label className="text-[10px] text-zinc-400 font-bold uppercase tracking-wider">Email Address</label>
            <div className="relative">
              <Mail className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-600" />
              <input
                type="email"
                required
                placeholder="you@company.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="w-full bg-white/[0.03] border border-white/5 pl-10 pr-4 py-2.5 rounded-xl text-xs text-zinc-200 outline-none focus:border-accent-blue transition-colors"
              />
            </div>
            {!isRegister && (
              <span className="text-[9px] text-zinc-500 block">Hint: include "mfa" in email to test Multi-Factor Auth flow.</span>
            )}
          </div>

          <div className="space-y-1">
            <label className="text-[10px] text-zinc-400 font-bold uppercase tracking-wider">Password</label>
            <div className="relative">
              <Lock className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-600" />
              <input
                type="password"
                required
                placeholder="••••••••"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full bg-white/[0.03] border border-white/5 pl-10 pr-4 py-2.5 rounded-xl text-xs text-zinc-200 outline-none focus:border-accent-blue transition-colors"
              />
            </div>
          </div>

          {isRegister && (
            <div className="space-y-1">
              <label className="text-[10px] text-zinc-400 font-bold uppercase tracking-wider">Workspace Role</label>
              <select
                value={role}
                onChange={(e) => setRole(e.target.value)}
                className="w-full bg-[#161D2F] border border-white/5 px-3 py-2.5 rounded-xl text-xs text-zinc-200 outline-none focus:border-accent-blue transition-colors"
              >
                <option value="ORGANIZER">Organizer (Host & Schedule Meetings)</option>
                <option value="ATTENDEE">Attendee (Join Meetings)</option>
                <option value="ADMIN">System Administrator (Full access)</option>
              </select>
            </div>
          )}

          <button
            type="submit"
            disabled={loading}
            className="w-full py-3 bg-accent-blue hover:bg-blue-600 rounded-xl text-white text-xs font-bold transition-all shadow-md shadow-accent-blue/15 flex items-center justify-center"
          >
            {loading ? (
              <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
            ) : isRegister ? (
              "Create Account"
            ) : (
              "Sign In"
            )}
          </button>
        </form>

        {/* SSO Divider */}
        <div className="flex items-center gap-3 my-4">
          <div className="flex-1 h-px bg-white/5" />
          <span className="text-[9px] font-bold text-zinc-600 uppercase tracking-widest">Or login with SSO</span>
          <div className="flex-1 h-px bg-white/5" />
        </div>

        {/* SSO Buttons */}
        <div className="grid grid-cols-2 gap-3">
          <button
            onClick={() => handleSSO("google")}
            className="flex items-center justify-center gap-2 border border-white/5 bg-white/[0.02] hover:bg-white/[0.05] p-2.5 rounded-xl text-xs font-semibold text-zinc-300 transition-colors"
          >
            <Chrome className="w-3.5 h-3.5 text-red-400" /> Google
          </button>
          <button
            onClick={() => handleSSO("github")}
            className="flex items-center justify-center gap-2 border border-white/5 bg-white/[0.02] hover:bg-white/[0.05] p-2.5 rounded-xl text-xs font-semibold text-zinc-300 transition-colors"
          >
            <Github className="w-3.5 h-3.5 text-zinc-400" /> GitHub
          </button>
        </div>

        {/* Form toggle */}
        <div className="text-center pt-2">
          <button
            onClick={() => setIsRegister(!isRegister)}
            className="text-[11px] font-semibold text-accent-blue hover:text-blue-400 transition-colors"
          >
            {isRegister ? "Already have an account? Sign In" : "Need an organization account? Sign Up"}
          </button>
        </div>
      </div>
    </div>
  );
}
